# This file was generated by https://github.com/kamilchm/go2nix v1.2.1
[
  {
    goPackagePath = "github.com/docopt/docopt-go";
    fetch = {
      type = "git";
      url = "https://github.com/docopt/docopt-go";
      rev = "ee0de3bc6815ee19d4a46c7eb90f829db0e014b1";
      sha256 = "0hlra7rmi5pmd7d93rv56ahiy4qkgmq8a6mz0jpadvbi5qh8lq6j";
    };
  }
  {
    goPackagePath = "github.com/mpoquet/go-prompt";
    fetch = {
      type = "git";
      url = "https://github.com/mpoquet/go-prompt";
      rev = "2861a1991fd3e68115d9534677e234d359240feb";
      sha256 = "0grx0n8aia006k13nqb2d0vg5g0789w0wciq86ra1qnmxhm82zyb";
    };
  }
  {
    goPackagePath = "github.com/pkg/term";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/term";
      rev = "bffc007b7fd5a70e20e28f5b7649bb84671ef436";
      sha256 = "0c9xnx7dyw7j890nm9av5fjpqjb129z7vbg3lw554vwnckc84x54";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "4fabf2fffcecfd47f802869b7b92d75e43c5a095";
      sha256 = "0p4r9wlwxx34dgldw2y22r40xw6zm6pminc6hza1kax2sg6k5vjl";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "04af85275a5c7ac09d16bb3b9b2e751ed45154e5";
      sha256 = "1al7hgvg34xbajds99ss5wmlndxbzzmz5l0wrg6wchvvfaiwxlx0";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "0c41d7ab0a0ee717d4590a44bcb987dfd9e183eb";
      sha256 = "1mff9l49dffsak7vxg3dzxlzkgm5nqfksh9cbsjpmngpc5pk0fbc";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "8e24a49d80f82323e1c4db1b5da3e0f31171a151";
      sha256 = "0zsdnyb8dy98jw6f9yn6g5gdhaqwk39hqridr0mh4dhwvwvlj724";
    };
  }
]
